export default function() {
  return [
    {
      name: 'Asahi Super Dry',
      type: 'Lager',
      country: 'Japan',
      state: '',
      abv: 5.0,
    },
    {
      name: 'Sapporo Premium',
      type: 'Lager',
      country: 'Japan',
      state: '',
      abv: 4.9,
    },
    {
      name: 'Tecate',
      type: 'Lager',
      country: 'Mexico',
      state: '',
      abv: 4.5,
    },
    {
      name: 'Magner\'s',
      type: 'Hard Cider',
      country: 'Ireland',
      state: '',
      abv: 4.5,
    },
    {
      name: 'Dogfish Head SeaQuench',
      type: 'Sour Ale',
      country: 'USA',
      state: 'Delaware',
      abv: '',
    },
    {
      name: '2 Towns Ciderhouse Pacific Pineapple',
      type: 'Hard Cider',
      country: 'USA',
      state: 'Oregon',
      abv: 5.0,
    },
    {
      name: '2 Towns Ciderhouse Ginja Ninja',
      type: 'Hard Cider',
      country: 'USA',
      state: 'Oregon',
      abv: 6.0,
    },
    {
      name: '2 Towns Ciderhouse Hard Apple Cider',
      type: 'Hard Cider',
      country: 'USA',
      state: 'Oregon',
      abv: 6.0,
    },
    {
      name: 'New Belgium Fat Tire',
      type: 'Amber Ale',
      country: 'USA',
      state: 'Colorado',
      abv: 5.2,
    },
    {
      name: 'Blue Moon',
      type: 'Wheat Beer',
      country: 'USA',
      state: 'Colorado',
      abv: 5.4,
    },
    {
      name: 'Goose Island Green Line',
      type: 'APA',
      country: 'USA',
      state: 'Illinois',
      abv: 5.4,
    },
    {
      name: 'Ace Perry',
      type: 'Hard Cider',
      country: 'USA',
      state: 'California',
      abv: 5.0,
    },
    {
      name: 'Right Bee Cider',
      type: 'Hard Cider',
      country: 'USA',
      state: 'Illinois',
      abv: 6,
    },
    {
      name: 'Goose Island 312 Urban Wheat',
      type: 'Wheat Beer',
      country: 'USA',
      state: 'Illinois',
      abv: 4.2,
    },
    {
      name: 'Leinenkugel\'s Summer Shandy',
      type: 'Fruit Beer',
      country: 'USA',
      state: 'Wisconsin',
      abv: 4.2,
    },
    {
      name: 'Burnt City Facemelter',
      type: 'IPA',
      country: 'USA',
      state: 'Illinois',
      abv: 7.0,
    },
    {
      name: 'Maui Pineapple Mana',
      type: 'Wheat Beer',
      country: 'USA',
      state: 'Hawaii',
      abv: 5.5,
    },
    {
      name: 'Virtue Rose',
      type: 'Hard Cider',
      country: 'USA',
      state: 'Michigan',
      abv: 6.7,
    },
    {
      name: 'Bavik Super Pils',
      type: 'Pilsner',
      country: 'Belgium',
      state: '',
      abv: 5.2,
    },
    {
      name: 'Rekorderlig Passionfruit',
      type: 'Hard Cider',
      country: 'Sweden',
      state: '',
      abv: 4.5,
    },
    {
      name: 'Owl\'s Brew Radler Wicked Watermelon',
      type: 'Fruit Beer',
      country: 'USA',
      state: 'New York',
      abv: 3.8,
    },
    {
      name: 'New Holland Dragon\'s Milk',
      type: 'Stout',
      country: 'USA',
      state: 'Michigan',
      abv: 11.0,
    },
    {
      name: 'Krombacher Pils',
      type: 'Pilsner',
      country: 'Germany',
      state: '',
      abv: 4.8,
    },
    {
      name: 'Amstel Light',
      type: 'Lager',
      country: 'Holland',
      state: '',
      abv: 3.5,
    },
    {
      name: 'Surly Furious',
      type: 'IPA',
      country: 'USA',
      state: 'Minnesota',
      abv: 6.7,
    },
    {
      name: 'Original Sin Black Widow',
      type: 'Hard Cider',
      country: 'USA',
      state: 'New York',
      abv: 6.0,
    },
    {
      name: 'Forbidden Root Strawberry Basil',
      type: 'Fruit Beer',
      country: 'USA',
      state: 'Illinois',
      abv: 5.0,
    },
    {
      name: 'Carlsberg',
      type: 'Lager',
      country: 'Denmark',
      state: '',
      abv: 5.0,
    },
    {
      name: 'Labatt Blue',
      type: 'Pilsner',
      country: 'Canada',
      state: '',
      abv: 4.7,
    },
    {
      name: 'Corona Extra',
      type: 'Lager',
      country: 'Mexico',
      state: '',
      abv: 4.5,
    },
    {
      name: 'Modelo Especial',
      type: 'Lager',
      country: 'Mexico',
      state: '',
      abv: 4.4,
    },
    {
      name: 'Negra Modelo',
      type: 'Lager',
      country: 'Mexico',
      state: '',
      abv: 5.4,
    },
    {
      name: 'Guinness Draught',
      type: 'Stout',
      country: 'Ireland',
      state: '',
      abv: 4.2,
    },
    {
      name: 'Shock Top Belgian White',
      type: 'Wheat Beer',
      country: 'USA',
      state: 'Missouri',
      abv: 5.4,
    },
    {
      name: 'Michelob ULTRA',
      type: 'Lager',
      country: 'USA',
      state: 'Missouri',
      abv: 4.2,
    },
    {
      name: 'Heineken',
      type: 'Lager',
      country: 'Holland',
      state: '',
      abv: 5.0,
    },
    {
      name: 'Ballast Point Grapefruit Sculpin',
      type: 'IPA',
      country: 'USA',
      state: 'California',
      abv: 7.0,
    },
    {
      name: 'Ballast Point Sour Wench',
      type: 'Sour Ale',
      country: 'USA',
      state: 'California',
      abv: 7.0,
    },
    {
      name: 'Dos Equis Lager',
      type: 'Pilsner',
      country: 'Mexico',
      state: '',
      abv: 4.2,
    },
    {
      name: 'Bohemia',
      type: 'Pilsner',
      country: 'Mexico',
      state: '',
      abv: 4.7,
    },
    {
      name: 'Pabst Blue Ribbon',
      type: 'Lager',
      country: 'USA',
      state: 'Wisconsin',
      abv: 4.74,
    },
    {
      name: 'Coors Light',
      type: 'Lager',
      country: 'USA',
      state: 'Colorado',
      abv: 4.2,
    },
    {
      name: 'Rolling Rock',
      type: 'Lager',
      country: 'USA',
      state: 'Missouri',
      abv: 4.4,
    },
    {
      name: 'Kirin Ichiban',
      type: 'Lager',
      country: 'Japan',
      state: '',
      abv: 5.0,
    },
    {
      name: 'Sapporo Black',
      type: 'Lager',
      country: 'Japan',
      state: '',
      abv: 5.0,
    },
    {
      name: 'Lucky Buddha Enlightened Beer',
      type: 'Lager',
      country: 'Australia',
      state: '',
      abv: 4.8,
    },
    {
      name: 'Kloud Original Gravity',
      type: 'Pilsner',
      country: 'South Korea',
      state: '',
      abv: 5.0,
    },
    {
      name: 'Tsingtao Beer',
      type: 'Lager',
      country: 'China',
      state: '',
      abv: 4.0,
    },
    {
      name: 'Beck\'s',
      type: 'Pilsner',
      country: 'Germany',
      state: '',
      abv: 5.0,
    },
    {
      name: 'Almaza Pilsner Beer',
      type: 'Pilsner',
      country: 'Lebanon',
      state: '',
      abv: 4.2,
    },
    {
      name: 'Stiegl Grapefruit Radler',
      type: 'Fruit Beer',
      country: 'Austria',
      state: '',
      abv: 2.5,
    },
    {
      name: 'Stiegl Pils',
      type: 'Lager',
      country: 'Austria',
      state: '',
      abv: 4.9,
    },
    {
      name: 'Strongbow Gold Apple',
      type: 'Hard Cider',
      country: 'England',
      state: '',
      abv: 5.0,
    },
    {
      name: 'Stella Artois',
      type: 'Pilsner',
      country: 'Belgium',
      state: '',
      abv: 5.0,
    },
    {
      name: 'Stella Artois Cidre',
      type: 'Hard Cider',
      country: 'Belgium',
      state: '',
      abv: 4.5,
    },
    {
      name: 'JK\'s The Pair Perry Cider',
      type: 'Hard Cider',
      country: 'USA',
      state: 'Michigan',
      abv: 5.5,
    },
    {
      name: 'Brooklyn Lager',
      type: 'Lager',
      country: 'USA',
      state: 'New York',
      abv: 5.2,
    },
    {
      name: 'Peroni Nastro Azzurro',
      type: 'Lager',
      country: 'Italy',
      state: '',
      abv: 5.1,
    },
    {
      name: 'Starcut Mosa',
      type: 'Hard Cider',
      country: 'USA',
      state: 'Michigan',
      abv: 4.3,
    },
    {
      name: 'Goose Island Soleil',
      type: 'Saison',
      country: 'USA',
      state: 'Illinois',
      abv: 5.5,
    },
    {
      name: 'Goose Island 312 Dry-Hopped',
      type: 'Wheat Beer',
      country: 'USA',
      state: 'Illinois',
      abv: 4.2,
    },
    {
      name: 'Sonoma Cider The Hatchet Hard Apple Cider',
      type: 'Hard Cider',
      country: 'USA',
      state: 'California',
      abv: 6.0,
    },
    {
      name: 'Sonoma Cider The Pitchfork Hard Pear Cider',
      type: 'Hard Cider',
      country: 'USA',
      state: 'California',
      abv: 6.0,
    },
    {
      name: 'Angry Orchard Crisp Apple Cider',
      type: 'Hard Cider',
      country: 'USA',
      state: 'Massachusetts',
      abv: 5.0,
    },
    {
      name: 'Angry Orchard Green Apple',
      type: 'Hard Cider',
      country: 'USA',
      state: 'Massachusetts',
      abv: 5.0,
    },
    {
      name: 'Stem Cider Chile Guava',
      type: 'Hard Cider',
      country: 'USA',
      state: 'Colorado',
      abv: 5.7,
    },
    {
      name: 'Solemn Oath Snaggletooth Bandana',
      type: 'IPA',
      country: 'USA',
      state: 'Illinois',
      abv: 6.5,
    },
    {
      name: 'Miller Lite',
      type: 'Lager',
      country: 'USA',
      state: 'Wisconsin',
      abv: 4.17,
    },
    {
      name: 'Miller High Life',
      type: 'Lager',
      country: 'USA',
      state: 'Wisconsin',
      abv: 4.6,
    },
    {
      name: 'Bud Light',
      type: 'Lager',
      country: 'USA',
      state: 'Missouri',
      abv: 4.2,
    },
    {
      name: 'Taiwan Beer Sweet Touch Lychee',
      type: 'Fruit Beer',
      country: 'Taiwan',
      state: '',
      abv: 3.5,
    },
    {
      name: 'Natural Light',
      type: 'Lager',
      country: 'USA',
      state: 'Missouri',
      abv: 4.2,
    },
    {
      name: 'Pacifico',
      type: 'Lager',
      country: 'Mexico',
      state: '',
      abv: 4.5,
    },
    {
      name: 'Redd\'s Apple Ale',
      type: 'Fruit Beer',
      country: 'USA',
      state: 'Georgia',
      abv: 5.0,
    },
    {
      name: 'Lost Coast Tangerine Wheat',
      type: 'Fruit Beer',
      country: 'USA',
      state: 'California',
      abv: 5.5,
    },
    {
      name: 'Samuel Smith\'s Organic Cherry',
      type: 'Fruit Beer',
      country: 'England',
      state: '',
      abv: 5.1,
    },
    {
      name: 'Goose Island Honker\'s Ale',
      type: 'English Bitter',
      country: 'USA',
      state: 'Illinois',
      abv: 4.3,
    },
    {
      name: 'Schlafly Merry Berry',
      type: 'Fruit Beer',
      country: 'USA',
      state: 'Missouri',
      abv: 6.0,
    },
    {
      name: 'Short\'s Soft Parade Shandy',
      type: 'Fruit Beer',
      country: 'USA',
      state: 'Michigan',
      abv: 4.2,
    },
    {
      name: 'Boulevard Ginger Lemon Radler',
      type: 'Fruit Beer',
      country: 'USA',
      state: 'Missouri',
      abv: 4.1,
    },
    {
      name: 'Shiner Ruby Redbird',
      type: 'Fruit Beer',
      country: 'USA',
      state: 'Texas',
      abv: 4.1,
    },
  ];
}
